function [] = TimeSeries(fileName)

%-------------------------------------------------------------------------------------------------------------------
% This file is part of Fugitive Emissions Abatement Simulation Toolkit aka FEAST
% Copyright {2016} {Chandler E. Kemp; Arvind P. Ravikumar; Adam R. Brandt} 

% FEAST is free software: you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% (at your option) any later version.
% FEAST is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
% You should have received a copy of the GNU General Public License
%  along with this program.  If not, see <http://www.gnu.org/licenses/>.
%--------------------------------------------------------------------------------------------------------------------

% timeSeries reads a results file generated by FEAST and produces a
% timeseries of the leakage for each LDAR program in the simulation.
% Inputs:
%   fileName    path to a results file as a string
% Outputs:
%   Figure 1    timeseries plot
load(fileName)

% Define the color scheme:
ColorSet = [ 140,21,21; 0,152,219 ; 0,155,118;  178,111,22; 83,40,79;  0,0,0; 77,79,83];
ColorSet = ColorSet/max(max(ColorSet));
set(0,'DefaultAxesColorOrder',ColorSet)

%% timeseries
% figure(1)
% clf
% Each variable here is loaded from the input file
plot(timeStruct.time,Leakage/GasField.SiteCount)

% title('Leakage Time Series')
xlabel('Time (days)')
ylabel('Total Leakage [g/s-well]')
legend(legendString,'No repair')
xlim([0,timeStruct.time(end)])
ylim([0,1])
%Improve appearance of the plot by thickening lines, etc:
plotfixer